In [1]:
import pandas as pd

In [2]:
import sqlite3

In [3]:
conn=sqlite3.connect('text.db')

In [4]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

In [5]:
df=pd.read_csv(url)

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.to_sql('titanic',conn,if_exists='replace',index=False)

891

In [10]:
pd.read_sql('SELECT *FROM titanic', conn)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [13]:
pd.read_sql('SELECT Name, Sex, Age, Survived FROM titanic', conn)

                                                  Name     Sex   Age  Survived
0                              Braund, Mr. Owen Harris    male  22.0         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                               Heikkinen, Miss. Laina  female  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                             Allen, Mr. William Henry    male  35.0         0
..                                                 ...     ...   ...       ...
886                              Montvila, Rev. Juozas    male  27.0         0
887                       Graham, Miss. Margaret Edith  female  19.0         1
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN         0
889                              Behr, Mr. Karl Howell    male  26.0         1
890                                Dooley, Mr. Patrick    male  32.0         0

[891 rows x 4 columns]

In [14]:
pd.read_sql('SELECT * FROM titanic WHERE Survived = 1 ORDER BY AGE DESC', conn )

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
1,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
2,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
3,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
4,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
337,728,1,3,"Mannion, Miss. Margareth",female,NaN,0,0,36866,7.7375,NaN,Q
338,741,1,1,"Hawksford, Mr. Walter James",male,NaN,0,0,16988,30.0000,D45,S
339,829,1,3,"McCormack, Mr. Thomas Joseph",male,NaN,0,0,367228,7.7500,NaN,Q
340,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
341,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C

In [19]:
result=pd.read_sql('SELECT Sex, Pclass, Survived FROM titanic', conn )

In [21]:
result.pivot_table(values='Survived', index='Sex', columns='Pclass', aggfunc='mean')

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [22]:
survived=pd.read_sql('SELECT * FROM titanic WHERE Survived =1', conn)

In [23]:
survived.pivot_table(values='PassengerId',index='Sex', columns='Pclass', aggfunc='count')

Pclass   1   2   3
Sex
female  91  70  72
male    45  17  47

In [27]:
survived['AgeGroup']=pd.cut(survived['Age'], bins=[0, 18, 35, 60, 100], labels=['child', 'young','adult','senior'])

In [28]:
survived.groupby('AgeGroup')['PassengerId'].count()

AgeGroup
child      70
young     137
adult      78
senior      5
Name: PassengerId, dtype: int64